#define WINVER 0x0601
#define _WIN32_WINNT_ 0x0601

/* AC/DC Power Flow Help. */

#include <stdlib.h>
//#ifndef WINDOWS
//#include <stdio.h>
//#else
#include "pfwstdio.h"
//#endif
#include <string.h>
#include "param.h"

#ifdef ANSIPROTO
void ErrorStop(char *Msg);
#else
void ErrorStop();
#endif

/* ---------------------- ErrorStop ------------------------------------ */
#ifdef ANSIPROTO
void ErrorStop(char *Msg)
#else
void ErrorStop(Msg)
char *Msg;
#endif
{
  fCustomPrint(stdout,"UW Continuation Power Flow (c)1992,1996,1999, 2006 C. Canizares, F. Alvarado and S. Zhang.\n");
  if (!NullName(Msg)) fCustomPrint(stdout,"Error: %s\n",Msg);
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"Usage:\n");
  fCustomPrint(stdout,"       Like any other UNIX program, i.e., command-line options (-option)\n");
  fCustomPrint(stdout,"       with redirection of output (>) from screen into files:\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"              uwpflow  [-options]  input_file   [[>]output_file]\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"Input file:\n");
  fCustomPrint(stdout,"       The input_file could be in WSCC/BPA/EPRI format (or Anarede's variation)\n");
  fCustomPrint(stdout,"       or IEEE common format (or Electrocon's variation) for the ac system.\n");
  fCustomPrint(stdout,"       Other AC formats may be used (see options below).\n");
  fCustomPrint(stdout,"       The dc data could be on either WSCC/BPA or multiterminal EPRI format,\n");
  fCustomPrint(stdout,"       although it just deals with the standard two-terminal HVDC problem.\n");
  fCustomPrint(stdout,"       The FACTS devices format was specifically designed for this program and\n");
  fCustomPrint(stdout,"       is explained in the help file and test systems provided with the program.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"Output files:\n");
  fCustomPrint(stdout,"       The program writes the solution into the output_file in ASCII.  It\n");
  fCustomPrint(stdout,"       can also write the solved case in a file in IEEE common format\n");
  fCustomPrint(stdout,"       using the -W or -w option (HVDC links are written in EPRI's ETMSP format\n");
  fCustomPrint(stdout,"       and FACTS devices are written in their own format).\n");
  fCustomPrint(stdout,"       Additional files can be created for post-processing analyses (see\n");
  fCustomPrint(stdout,"       options below), such as the bifurcation diagram (nose curve) in column\n");
  fCustomPrint(stdout,"       form for plotting with MATLAB or Octave, Jacobians for SMMS or\n");
  fCustomPrint(stdout,"       MATLAB/Octave studies, etc.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"Solution Technique:\n");
  fCustomPrint(stdout,"       The power flows are solved with simultaneous N-R, allowing for\n");
  fCustomPrint(stdout,"       asynchronous systems, area interchange, remote voltage control, and\n");
  fCustomPrint(stdout,"       local and remote regulating transformers (LTCs and phase shifters\n");
  fCustomPrint(stdout,"       controlling voltages, angles, and/or active and reactive power flows).\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"Options:\n");
  fCustomPrint(stdout,"         -a     Turns off tap and angle limits in regulating transformers.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -A     Turns off interchange area control.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -b     Solve base case before changing the loading factor lambda.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -Bnum  PQ bus number 'num' where the voltage is fixed in order to\n");
  fCustomPrint(stdout,"                find the loading factor (lambda) for voltage collapse studies.\n");
  fCustomPrint(stdout,"                Must be used with -K and -v options.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -cfile Increases the loading factor lambda using a continuation\n");
  fCustomPrint(stdout,"                method for finding voltage profiles.\n");
  fCustomPrint(stdout,"                The output (optional 'file') is a list of max. 8 ac voltages\n");
  fCustomPrint(stdout,"                that change the most, plus 3 additional variables for each dc\n");
  fCustomPrint(stdout,"                bus and for each generator (see -e and -3 options).\n");
  fCustomPrint(stdout,"                Must be used with the -K option.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -Cfile Direct method studies, i.e., find the max. loading factor\n");
  fCustomPrint(stdout,"                lambda for a given generation and load direction. The base case\n");
  fCustomPrint(stdout,"                loading can be initialized using the -L option; however, the\n");
  fCustomPrint(stdout,"                program calculates an initial loading of the system before the\n");
  fCustomPrint(stdout,"                direct method is applied.  The left e-vector is written in\n");
  fCustomPrint(stdout,"                'file' (optional).  Must be used with the -K option.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -d     Generates some debug output.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -Dfile Read load model data from 'file', using Ontario Hydro (OH)\n");
  fCustomPrint(stdout,"                format, which is based on the load model: Pl=Pn*V^a+Pz*V^2\n");
  fCustomPrint(stdout,"                                                          Ql=Qn*V^b+Qz*V^2\n");
  fCustomPrint(stdout,"                If a bus is not defined in the list, Pn=Qn=0 is assumed.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -e     Output 3 dc variables per dc link, and 3 internal variables for\n");
  fCustomPrint(stdout,"                generators in the output list during the continuation process\n");
  fCustomPrint(stdout,"                (see the -i option).\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -Efile Print in 'file' the continuation method direction vector at the\n");
  fCustomPrint(stdout,"                maximum loading factor (PoC right e-vector).\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -fnum  Output Sensitivity Factors (SF) and Voltage Sensitivity Factors\n");
  fCustomPrint(stdout,"                (VSF and tangent vector) during continuation computations.\n");
  fCustomPrint(stdout,"                The number 'num' defines the bus for which the voltage entry\n");
  fCustomPrint(stdout,"                and rank in the tangent vector are printed out (Tangent Vector\n");
  fCustomPrint(stdout,"                Index); if this number is not defined, the program chooses the\n");
  fCustomPrint(stdout,"                bus with the maximum initial voltage entry in the tangent\n");
  fCustomPrint(stdout,"                vector.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -Fval  Stability/sparsity value 'val' for factorization (def. 0.01).\n");
  fCustomPrint(stdout,"                A value of 0 means choose a pivot based on sparsity only;\n");
  fCustomPrint(stdout,"                a value of 1 means choose a pivot based on stability only.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -g     Force Q in generators to zero when reading data in IEEE\n");
  fCustomPrint(stdout,"                common format, since sometimes a value of Qg creates\n");
  fCustomPrint(stdout,"                convergence problems.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -G     Turns off recovery from some ac device limits in the program.\n");
  fCustomPrint(stdout,"                For example, the program allows to recover voltage control\n");
  fCustomPrint(stdout,"                after a Q-limit is reached by monitoring the voltage; this\n");
  fCustomPrint(stdout,"                option eliminates that possibility.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -h     Prints this message in standard output.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -Hfile Increases the loading factor lambda using a parameterized\n");
  fCustomPrint(stdout,"                continuation method for finding voltage profiles.\n");
  fCustomPrint(stdout,"                The output (optional 'file') is a list of max. 8 ac voltages\n");
  fCustomPrint(stdout,"                that change the most, plus 3 additional variables for each dc\n");
  fCustomPrint(stdout,"                bus (see -e option).  Must be used with the -K option.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -ifile List of numbers and names in 'file' for printing variable\n");
  fCustomPrint(stdout,"                profiles with the -c and -H options. The input format is:\n");
  fCustomPrint(stdout,"                Number Bus/AreaName [VarType].\n");
  fCustomPrint(stdout,"                Use zero when either the number or the name are unknown.\n");
  fCustomPrint(stdout,"                If Name has spaces, wrap it in double or single quotes.\n");
  fCustomPrint(stdout,"                VarType is optional and can be: V for voltage (default),\n");
  fCustomPrint(stdout,"                D for angle, PG for MW generated, QG for Mvar generated,\n");
  fCustomPrint(stdout,"                PL for MW load, QL for Mvar load, or PA for MW area flow.\n");
  fCustomPrint(stdout,"                If Name and Number are both equal to 0 and VarType is either \n");
  fCustomPrint(stdout,"                PL, QL, PG or QG, the program will print the corresponding \n");
  fCustomPrint(stdout,"                total load or generation in MW or Mvar.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -I     AC input data in IEEE common format.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -Ip    AC input data in IEEE common format with Power World\n");
  fCustomPrint(stdout,"                modifications.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -jname Write the Jacobian of the solved case in I J VALUE format in\n");
  fCustomPrint(stdout,"                'name.jac'.  The equation mismatches and the system variables\n");
  fCustomPrint(stdout,"                are also written in 'name.mis' and 'name.var', respectively.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -Jname With the -B option, it generates the Jacobian, mismatches and\n");
  fCustomPrint(stdout,"                variables corresponding to the system without the loading\n");
  fCustomPrint(stdout,"                factor as a variable.  For PoC studies (-C option) it generates\n");
  fCustomPrint(stdout,"                the nxn system Jacobian, mismatches and variables; for the\n");
  fCustomPrint(stdout,"                complete (2n+1)x(2n+1) PoC Jacobian, use the -j option.  The\n");
  fCustomPrint(stdout,"                corresponding Jacobian, mismatches and variables are written\n");
  fCustomPrint(stdout,"                in I J VALUE format in 'name.jac', 'name.mis' and 'name.var',\n");
  fCustomPrint(stdout,"                respectively.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -kval  Factor 'val' used in the homotopy continuation method for\n");
  fCustomPrint(stdout,"                finding the increments in the loading factor lambda (def. 1).\n");
  fCustomPrint(stdout,"                Must be used with the -c and -H options.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -Kfile Read generation and load distribution factors from 'file'.\n");
  fCustomPrint(stdout,"                All data is assumed p.u. and must be separated by spaces: \n");
  fCustomPrint(stdout,"                BusNumber BusName DPg Pnl Qnl PgMax [Smax Vmax Vmin Pzl Qzl].\n");
  fCustomPrint(stdout,"                If the input variables DPg, Pnl, Qnl or PgMax are unknown, give\n");
  fCustomPrint(stdout,"                them a value of zero; Smax, Vmax, Vmin, Pzl and Qzl are\n");
  fCustomPrint(stdout,"                optional.\n");
  fCustomPrint(stdout,"                The generation factors DPg are normalized for each area, i.e.,\n");
  fCustomPrint(stdout,"                ||DPg||=1 per area.\n");
  fCustomPrint(stdout,"                The load is represented by:\n");
  fCustomPrint(stdout,"                     Pl=(Pn+Pnl*lambda)*V^a+(Pz+Pzl*lambda)*V^2\n");
  fCustomPrint(stdout,"                     Ql=(Qn+Qnl*lambda)*V^b+(Qz+Qzl*lambda)*V^2\n");
  fCustomPrint(stdout,"                where Pn, Qn, Pz, Qz, a, and b are defined with the -D option,\n");
  fCustomPrint(stdout,"                and lambda corresponds to the loading factor.  If the -D option\n");
  fCustomPrint(stdout,"                is not used, the load model default values are: a=b=0, Pz=Qz=0.\n");
  fCustomPrint(stdout,"                Buses not in the list are assumed to have zero distribution\n");
  fCustomPrint(stdout,"                factors.   If BusName has spaces, wrap it in double or single\n");
  fCustomPrint(stdout,"                quotes.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -lfile Write standard error output to 'file' (log file).\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -Lval  Loading factor 'val' (def. 0).  Simulates load changes in\n");
  fCustomPrint(stdout,"                conjunction with the load distribution factors (-K option).\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -m     Output continuation profiles in MATLAB/Octave format.  If TEF profiles\n");
  fCustomPrint(stdout,"                are needed, use the -O option.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -Mnum  Number 'num' of max. N-R iterations, overriding input data\n");
  fCustomPrint(stdout,"                (default 50).\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -n     Turns off all ac system limits.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -N     Turns off all ac system controls.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -otol  The tolerance 'tol' controls the application of limits during\n");
  fCustomPrint(stdout,"                the continuation process.  The smaller this value, the more\n");
  fCustomPrint(stdout,"                steps required of the continuation method (default 0.000001).\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -Onum  This option is used together with -m to output ac/dc TEF\n");
  fCustomPrint(stdout,"                information during the continuation method to determine\n");
  fCustomPrint(stdout,"                the energy profiles with the help of MATLAB or Octave. The integer\n");
  fCustomPrint(stdout,"                'num' corresponds to the number of significant digits in TEF\n");
  fCustomPrint(stdout,"                (default and min. 6; max. 10).\n");
  fCustomPrint(stdout,"                If the system has HVDC links, the program defaults the PI\n");
  fCustomPrint(stdout,"                controller gains (Kp and Ki) of all HVDC converters for dc \n");
  fCustomPrint(stdout,"                computations to 'typical' values of Ki=75 and Kp=1.  These\n");
  fCustomPrint(stdout,"                values can later be changed in the MATLAB/Octave output file.\n");
  fCustomPrint(stdout,"                The program also generates two MATLAB/Octave '.m' files needed for\n");
  fCustomPrint(stdout,"                plotting and computation of the ac/dc energy function, namely,\n");
  fCustomPrint(stdout,"                'addtotef.m' (only if dc lines present) and 'tefprof.m'.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -p     Turns off P and Q limits in regulating transformers.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -P     Turns off P and Q control by regulating transformers.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -q     Turns off Q limits in PV buses.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -qx    Turns off V limits in reactance-controlled (BX) buses.\n");
  fCustomPrint(stdout,"                These buses are defined in the ETMSP/EPRI/BPA input data file.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -qz    Turns off Q limits in reactance-controlled (BZ) buses.\n");
  fCustomPrint(stdout,"                These buses are defined in the Italian ADD input data file.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -Q     Turns off remote voltage generator control.  Generators\n");
  fCustomPrint(stdout,"                will control their terminal voltages at their given values.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -QX    Turns off remote voltage control in reactance-controlled (BX)\n");
  fCustomPrint(stdout,"                buses.  The local bus voltage will be used for the control.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -r     Turns off V limits in regulating transformers and PV buses.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -R     Turns off V control by regulating transformers.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -s     Suppress ASCII output_file.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -Sval  Stop value 'val' for the loading factor lambda in the continua-\n");
  fCustomPrint(stdout,"                tion method (-c and -H options), in p.u. of the maximum lambda.\n");
  fCustomPrint(stdout,"                The default is 0 for a complete trace of the bifurcation\n");
  fCustomPrint(stdout,"                diagram (min. 0; max. 1, i.e., lambda maximum).\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -ttol  If the relative error of two consecutive iteration mismatches\n");
  fCustomPrint(stdout,"                is larger than 'tol', voltage limits and regulating transformer\n");
  fCustomPrint(stdout,"                limits are applied (default 0.1).\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -Ttol  P.U. tolerance 'tol' for N-R method (default 1e-4).\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -uval  Value 'val' of the tolerance used to reduce the number of equa-\n");
  fCustomPrint(stdout,"                tions in the continuation method (-c and -H options), based on\n");
  fCustomPrint(stdout,"                the tangent vector technique.\n");
  fCustomPrint(stdout,"                The default is 1e-3 (min. 0 or no reduction, max. 0.2).\n");
  fCustomPrint(stdout,"                WARNING: This option might produce cycling, back-tracking, or\n");
  fCustomPrint(stdout,"                         singularity problems. If this happens, increase the\n");
  fCustomPrint(stdout,"                         number of steps in the -U option and/or reduce the\n");
  fCustomPrint(stdout,"                         value of 'val' in -u. \n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -Unum  Number 'num' of steps of the continuation method (-c and -H\n");
  fCustomPrint(stdout,"                options) between system reductions.  Used with the -u option.\n");
  fCustomPrint(stdout,"                The default number is 10 (min. 2, max. 100).\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -vmag  Voltage magnitude 'mag' at the first PQ bus (unless otherwise\n");
  fCustomPrint(stdout,"                specified by -B option) to find the corresponding lambda\n");
  fCustomPrint(stdout,"                for voltage collapse studies.  Must be used with -K option.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -Vfile Read initial guesses for ac and dc variables from 'file'.\n");
  fCustomPrint(stdout,"                The data must be separated by spaces, i.e.,\n");
  fCustomPrint(stdout,"                BusNumber BusName V_mag V_ang(deg), for ac buses, and\n");
  fCustomPrint(stdout,"                BusNumber BusName Variables Values, for dc buses.\n");
  fCustomPrint(stdout,"                For defining the dc variable, use the same EPRI format used\n");
  fCustomPrint(stdout,"                to define the control modes in the dc lines (e.g., ALGAPA,\n");
  fCustomPrint(stdout,"                would represent the dc variables Alpha, Gamma and Power);\n");
  fCustomPrint(stdout,"                the values must be given in standard units, i.e., MW, MVAR, KV,\n");
  fCustomPrint(stdout,"                Amp, deg.  If the input variables are unknown give them a value\n");
  fCustomPrint(stdout,"                of zero.  If BusName has spaces, wrap it in double or single\n");
  fCustomPrint(stdout,"                quotes.\n");
  fCustomPrint(stdout,"                If no 'file' name is given, the system is given a 'flat' start.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -wfile Write solved case into 'file' using IEEE CARD common format.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -Wfile Similar to -w option, but the solved case is written in 'file'\n");
  fCustomPrint(stdout,"                using IEEE TAPE common format.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -x     Do not use the distributed slack bus concept during the solution\n");
  fCustomPrint(stdout,"                process, i.e., use only one slack bus.  The generator powers\n");
  fCustomPrint(stdout,"                change based only on the direction defined in the K file and\n");
  fCustomPrint(stdout,"                the load level, as defined by the loading factor lambda.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -X     Do not enforce maximum active generation limits (PgMax).\n");
  fCustomPrint(stdout,"                See -K option.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -yfile Print in 'file' an approximation of the left e-vector of the\n");
  fCustomPrint(stdout,"                smallest real |e-value| at the current operating point.\n");
  fCustomPrint(stdout,"                Works with the -c/-H and -z options as well.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -Yfile Print in 'file' an approximation of the right e-vector of the\n");
  fCustomPrint(stdout,"                smallest real |e-value| at the current operating point.\n");
  fCustomPrint(stdout,"                Works with the -c/-H and -z options as well.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -znum  Stop continuation method after 'num' steps.  Together with the\n");
  fCustomPrint(stdout,"                -Z option, it can be used to print a tangent vector for a\n");
  fCustomPrint(stdout,"                particular value of the loading parameter lambda.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -Zfile Print in 'file' the normalized tangent vector to the\n");
  fCustomPrint(stdout,"                bifurcation manifold at step 'num' of the continuation method\n");
  fCustomPrint(stdout,"                (as defined by -z).  It is used with the -c or -H options.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -0name Print in MATLAB/Octave format the Jacobian matrices needed to compute\n");
  fCustomPrint(stdout,"                several voltage stability indices. These matrices are printed\n");
  fCustomPrint(stdout,"                in the files 'name#.m', where # stands for the step number in\n");
  fCustomPrint(stdout,"                the continuation method (-c or -H options).\n");
  fCustomPrint(stdout,"                A file 'name.m' is also created with all the MATLAB/Octave\n");
  fCustomPrint(stdout,"                instructions to compute and plot 6 distinct indices:\n");
  fCustomPrint(stdout,"                   * Minimum |e-value| and singular value for full matrix.\n");
  fCustomPrint(stdout,"                   * Minimum |e-value| and singular value for reduced Q matrix.\n");
  fCustomPrint(stdout,"                   * Test function and reduced determinant for a given bus\n");
  fCustomPrint(stdout,"                     (-1 option).\n");
  fCustomPrint(stdout,"                The program generates the MATLAB/Octave 'inviter.m' file needed for\n");
  fCustomPrint(stdout,"                the computation of these indices.\n");
  fCustomPrint(stdout,"                WARNING: This option generates a lot of output files that might\n");
  fCustomPrint(stdout,"                         clutter your system; it must be used with caution.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -1num  Used with -0 option, and defines the load bus at which the test\n");
  fCustomPrint(stdout,"                functions are computed.  If this option is not used, or if the\n");
  fCustomPrint(stdout,"                bus 'num' does not correspond to a load bus, the program\n");
  fCustomPrint(stdout,"                chooses the bus with the maximum voltage entry in the initial\n");
  fCustomPrint(stdout,"                tangent vector.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -2num  Define the number 'num' of steps used to determine the\n");
  fCustomPrint(stdout,"                change of direction of the loading parameter lambda in\n");
  fCustomPrint(stdout,"                the continuation method (-c or -H options) due to voltages\n");
  fCustomPrint(stdout,"                increasing after Q-limits are encountered (default 5).\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -3file Read generator steady-state data from 'file' using free format:\n");
  fCustomPrint(stdout,"                BusNumber BusName Ra Xd Xq Ia_max Eq_max Eq_min\n");
  fCustomPrint(stdout,"                For BusNames with spaces, wrap the word in double or single\n");
  fCustomPrint(stdout,"                quotes.  The program uses either the BusNumber or the BusName\n");
  fCustomPrint(stdout,"                to identify the bus; if one of this is not known, give it a 0\n");
  fCustomPrint(stdout,"                value.  For round-rotor machines, make Xd=Xq, or define Xq=0.\n");
  fCustomPrint(stdout,"                The program assumes the following default values: Ra=0, Xq=<Xd,\n");
  fCustomPrint(stdout,"                Ia_max=large, Eq_max=large, Eq_min=0.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -4     Turns off Eq limits in all generators.  See -3 option.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -5     Turns off Ia limits in all generators.  See -3 option.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -6file AC input data in ITALIAN format. If 'file' name is given,\n");
  fCustomPrint(stdout,"                a COLAS ADD file is read, which defines: new bus kV levels; \n");
  fCustomPrint(stdout,"                min. and max. bus voltages; load voltage coefficients 'a' and \n");
  fCustomPrint(stdout,"                and 'b', i.e.,\n");
  fCustomPrint(stdout,"                     Pl=(Pn+Pnl*lambda)*V^a \n");
  fCustomPrint(stdout,"                     Ql=(Qn+Qnl*lambda)*V^b \n");
  fCustomPrint(stdout,"                pilot nodes and generators for secondary voltage control \n");
  fCustomPrint(stdout,"                (-# option); and generator and load directions. \n");
  fCustomPrint(stdout,"                This file may be used instead of the -K and -D files; however,\n");
  fCustomPrint(stdout,"                these files take precedence over the ADD file in defining \n");
  fCustomPrint(stdout,"                similar variables for collapse studies.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -7     Enforce Vmax and Vmin on system buses during the continuation\n");
  fCustomPrint(stdout,"                process (-c or -H options).\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -8     Enforce Imax limits on transmission elements during the \n");
  fCustomPrint(stdout,"                continuation process (-c or -H options).\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -9     Do not enforce maximum power generation limits (Smax).\n");
  fCustomPrint(stdout,"                See -K option.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -$val  Define the base power value 'val', overriding the value given\n");
  fCustomPrint(stdout,"                in the input data file.\n");
  fCustomPrint(stdout,"\n");
  fCustomPrint(stdout,"         -#     Use secondary voltage control as defined by ENEL, i.e., remote\n");
  fCustomPrint(stdout,"                voltage control of pilot buses by generators with participation\n");
  fCustomPrint(stdout,"                factors defined as: \n");
  fCustomPrint(stdout,"                  * over-excited  -> q_i=Qmax_i/Sum Qmax of pilot bus gens.\n");
  fCustomPrint(stdout,"                  * under-excited -> q_i=Qmin_i/Sum Qmin of pilot bus gens.\n");
  fCustomPrint(stdout,"\n");
  if (!NullName(Msg)) stopExecute(ERROREXIT);
}


