name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: OpportunityLiu/github-action-setup-xmake@master
    - name: make
      run: xmake
    - name: test
      run: xmake r uwpflow -I ieee300.cf
